### ISSUE TITLE
User blocking

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#11]
**Suggestion:** _"Implement my block script lol. Repo: https://github.com/CosignCosine/KABlock"_
**Author:** Scott

**Comment by JettBurns14** [comment]
A block button on the user's profile above or below the "report" button would work nicely.

**Comment by CosignCosine** [comment]
If this were to be a permenant thing, there needs to be a permenant solution to blocking users— currently I'm storing the blocked users in LS. Was researching dynamic json creation to no avail. I've also thought of storing blocks by the user's fkey on another server, again to no avail.
