### ISSUE TITLE
Leave extension popup open when opening notifications

### ISSUE THREAD

**Issue by ShadowKA** [ka-extension/ka-extension-ts#110]
When you open notifications with Ctrl (or Command) + Click, the extension window closes. It would be helpful to be able to use Ctrl/Command + Click to open notifications without that window closing (eliminating having to reopen the extension window to open another notification).

**Comment by lukekrikorian** [comment]
Opening/closing the popup is controlled by the browser, so I'm not sure we can really do anything to fix this.
