### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#13]
**Suggestion:** _"Autocompletion when typing like before KA updated the editor."_
**Author:** Aqil

**Comment by JettBurns14** [comment]
@EthanLuisMcDonough you said this would basically do it?
`ScratchpadAutosuggest.enableLiveCompletion = e => true`

**Comment by MatthiasSaihttam** [comment]
Added in #131. (Not published yet.)
