### ISSUE TITLE
Add "Copy Link" button to KA program threads

### ISSUE THREAD

**Issue by lukekrikorian** [ka-extension/ka-extension-ts#138]

**Comment by An0n3m0us** [comment]
I don't really see why this would be useful, as one can simply right-click on the thread (or the comments within) to copy the link.

**Comment by lukekrikorian** [comment]
Can they? We don't have code for that and I don't believe KA does either.

**Comment by An0n3m0us** [comment]
Threads/comments on projects can be copied using the element indicated in the screenshot below:

![image](https://user-images.githubusercontent.com/49789044/112426975-c8199b00-8d30-11eb-9449-11b8fc235e28.png)

Is this feature request referring to something else?

**Comment by lukekrikorian** [comment]
You're right, my bad! I believe this issue was created before the discussion UI update.

**Comment by MatthiasSaihttam** [comment]
I think it was possible to copy a permalink with a right-click before, and this was in reference to adding a dedicated button to the page DOM. I don’t know, it doesn’t seem super useful to me.
