### ISSUE TITLE
Program modifications don't run on Challenge programs

### ISSUE THREAD

**Issue by MatthiasSaihttam** [ka-extension/ka-extension-ts#155]
When viewing a Challenge, like [Challenge: Simple Snowman](https://www.khanacademy.org/computing/computer-programming/programming/drawing-basics/pc/challenge-simple-snowman), the `onProgramPage` function doesn't run. I'm pretty sure this is because there's no discussion package loaded on that page. We might be able to switch to checking for the scratchpads package.

**Comment by An0n3m0us** [comment]
Broken because of #217

**Comment by An0n3m0us** [comment]
Is it fixed now?

![image](https://user-images.githubusercontent.com/49789044/112685139-0bc4ef80-8e6c-11eb-8513-23231448d300.png)

**Comment by MatthiasSaihttam** [comment]
Yes it is, thank you.
