### ISSUE TITLE
Add ambiance theme

### ISSUE THREAD

**Issue by cursorweb** [ka-extension/ka-extension-ts#156]
I would like an ambiance theme, please. (Project here showing the ambiance theme: https://www.khanacademy.org/computer-programming/inspector-free-html-editor-v45/6637092418158592)

**Comment by lukekrikorian** [comment]
Feel free to make a PR adding this change, we'll review it as soon as we can. Other than that, it may or may not get added, as this isn't exactly a high-priority change.

**Comment by MatthiasSaihttam** [comment]
I know Edward had also requested the Idle Fingers theme.

**Comment by MatthiasSaihttam** [comment]
Closed by #158 being merged.
