### ISSUE TITLE
Project Settings button is gone

### ISSUE THREAD

**Issue by lukekrikorian** [ka-extension/ka-extension-ts#171]
![image](https://user-images.githubusercontent.com/22383417/53894523-38e0a400-3ffe-11e9-8289-e8f520f7d1f4.png)

The project settings button is not showing up on project pages

**Comment by MatthiasSaihttam** [comment]
Khan Academy appears to have removed or renamed `KAdefine`, so all attempts to load data with it are failing.

**Comment by lukekrikorian** [comment]
Wow, I didn't realize it was that large a change we were working with. It looks like they've completely moved to webpack - at least from what I can see.

**Comment by Foxbyte14** [comment]
Ya the whole extension is broke except the fact you can see your notifs in the pop up but it dosn't notify you
