### ISSUE TITLE
Editor themes broken.

### ISSUE THREAD

**Issue by athaun** [ka-extension/ka-extension-ts#177]
The toggle editor, toggle editor settings, and themes are gone, as well as the extra wide editor, the only thing that is working is the notifications dropdown and instant replies. Is this a temporary and intentional, or did a KA update break something?
Thanks, Asher

**Comment by MatthiasSaihttam** [comment]
It’s a KA update that broke stuff. See #176

**Comment by athaun** [comment]
ok, thanks
