### ISSUE TITLE
Program badges earned

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#18]
**Suggestion:** _"Display what badges a program has earned, just like how questions/answers have."_
**Author:** Light Runner

**Comment by An0n3m0us** [comment]
Now that all of the project-related badges have been retired, is there a point to doing this?

**Comment by JettBurns14** [comment]
I don't see a point either, the original idea was to display those badges on current programs across the website as they earned votes, but that won't work now. Thanks for pointing this out, closing.
