### ISSUE TITLE
Hovercards with streak

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#2]
**Suggestion:** _"Add an orange box to hovercards with the user's streak."_
**Author:** Light Runner

![image](https://user-images.githubusercontent.com/24257648/39153567-21855968-4711-11e8-84b1-e467dd1c3912.png)

**Comment by JettBurns14** [comment]
Note: The user [API endpoint](https://www.khanacademy.org/api/internal/user/profile?format=pretty&username=) currently doesn't provide us with the user's current streak, `.streakLength` is always 0. Until this is fixed, this suggestion will have to wait.

**Comment by An0n3m0us** [comment]
It is possible to get a users current streak by reading the `streakLastLength` variable.

**Comment by JettBurns14** [comment]
@An0n3m0us you are partly correct, but that variable supplied the longest streak they last had, which could be a current OR past streak that was since broken. Unfortunately, streaks were [removed in January 2021](https://support.khanacademy.org/hc/en-us/articles/360054115071-Update-Streaks-are-going-away-on-January-4-2021) as I'm sure you know, so I'm closing this now.

Regardless, thanks for your input, and perhaps take a look at some other open issues on this project!
