### ISSUE TITLE
View notifs in popup

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#23]
**Suggestion:** _"Shouldn't you be able to see your notification(s) by just clicking on the extension? That would be better."_
**Authors:** DCZ_pro2 and Jett

**Comment by JettBurns14** [comment]
Forgot to make a PR with major changes, but the first batch of updates is [here](https://github.com/ka-extension/ka-extension-ts/commit/5e47f3bb619c9151bcc0f53bde516d63a4f5ec37).

I'll make a followup PR with some minor changes and that should be when I mark this done.

**Comment by lukekrikorian** [comment]
@JettBurns14 can we close this now?

**Comment by CosignCosine** [comment]
excuse me i am O F F E N D E D by the fact that you would D A R E close this before it needs to be closed W O W

**Comment by JettBurns14** [comment]
I think I’ll close this when I completely finish the notification viewer.
