### ISSUE TITLE
KA bookmarks

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#25]
**Suggestion:** _"When you click on the extension icon, add a link to the Khan Academy dashboard and another custom KA link the user can pick."_
**Author:** Granttwin

![image](https://user-images.githubusercontent.com/24257648/39319218-0b99ffbe-4946-11e8-9744-29eca5e6d2cb.png)

**Comment by lukekrikorian** [comment]
Duplicate of #26.
