### ISSUE TITLE
Change/remove Donate button

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#27]
**Suggestion:** _"Make this button say something else, or remove it."_
**Author:** Light Runner

![image](https://user-images.githubusercontent.com/24257648/39319480-c29e4242-4946-11e8-925c-a8428ef34c23.png)

**Comment by lukekrikorian** [comment]
I'm closing this because it doesn't really seem like a productive feature to create and maintain.
