### ISSUE TITLE
extension does not let me vote

### ISSUE THREAD

**Issue by rechiheaghie** [ka-extension/ka-extension-ts#271]
I click the upvote button (on a project) and nothing happens

**Comment by bhavjitChauhan** [comment]
This is probably because you're using the Khan Academy Notifications extension. I've submitted a pull request to that project to fix the issue.

You can track progress there:
https://github.com/eliasmurcray/ka-notifications/pull/26

**Comment by bhavjitChauhan** [comment]
The fix is live. If you're still having issues try manually updating the Khan Academy Notifications extension and make sure you're on version 3.0.8.
