### ISSUE TITLE
More rows for spin-offs

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#32]
**Suggestion:** _"When you're looking at spinoffs, make them like the HL with as many projects as possible on the page instead of just a double row. It will save time having like twice as many instead of having to load more projects more often."_
**Author:** Legolas

![image](https://user-images.githubusercontent.com/24257648/39320628-4a01bce8-494a-11e8-96f7-807695908662.png)

**Comment by An0n3m0us** [comment]
This is already implemented onto KA, as far as I can see.
