### ISSUE TITLE
Basically, fix this.

### ISSUE THREAD

**Issue by CosignCosine** [ka-extension/ka-extension-ts#38]
![image](https://user-images.githubusercontent.com/14265554/39449423-fd835684-4c95-11e8-9ce5-189a55ba4934.png)

**Comment by CosignCosine** [comment]
The wrapping is basically hecked.

**Comment by JettBurns14** [comment]
Ok, the text just needs to be wrapped somehow. Maybe cut up long words into sections no longer than say 40 characters, and add breaks between these sections.

**Comment by CosignCosine** [comment]
Actually (I haven't tested it yet) this may be able to be fixed by adding `word-wrap: break-word;` to the notification div style. One second, testing it out...

**Comment by CosignCosine** [comment]
However, it **can** be fixed by adding `word-break: break-all;` to the notification div style. 

```document.querySelectorAll('[id^="content-"]').forEach(function(e){
e.style.wordBreak = "break-all";
})```
