### ISSUE TITLE
Program width problem

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#8]
**Suggestion:** _"[#624](https://github.com/Khan/live-editor/issues/624), introduced in the Bibliotron update, it's an issue with KA's CSS.
On the chrome version of the extension, adding the following code into the widenProgram function fixes the issue:"_
```
var o = document.getElementById("output");
if (o) {
    o.style.width = "100%";
}
```

**Author:** Matthias

![image](https://user-images.githubusercontent.com/24257648/39157339-081954f2-4720-11e8-8d1a-e71ffd2d49fb.png)

**Comment by lukekrikorian** [comment]
Closing this because it would introduce fundamentally different functionality only for extension users, needs to be fixed by KA.
