### ISSUE TITLE
KA Extention Notifications Not Working

### ISSUE THREAD

**Issue by rocketbear27** [ka-extension/ka-extension-ts#84]
The Khan Academy extension has currently trouble displaying notifications from Khan Academy. I rely on this extension to check for notifications from other users. I recently checked the extension when there was no red notifs box on the extension icon in the browser bar. Then I opened the Khan Academy website when there was like 2-3 notifs waiting.

**Comment by lukekrikorian** [comment]
For notifications in the badge to work, you need to have signed into KA at least once for that browser session. Did the badge update once you signed in?

**Comment by rocketbear27** [comment]
@lukekrikorian,
do you mean signing in to KA as logged in where you can view your profile and projects? Because I had already signed in. Now I update the extension to the latest version, so problems did not occur.

**Comment by lukekrikorian** [comment]
Closing this as it seems to be fixed in 4.0
