### ISSUE TITLE
Show entire notification

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#9]
**Suggestion:** _"Show the entire notification not just a cutoff snippet (helpful to see the content of deleted messages)."_
**Author:** Shadow

**Comment by ShadowKA** [comment]
I don't know how hard this would be to do, but it it seems like it should only open on hover/click of a button or something so there's not a bunch of differently sized notifications.

**Comment by ShadowKA** [comment]
The extension now shows the full content in its notification tab. This could probably be closed.
